{% set component_name = "gazebo" %}
{% set base_name = "libignition-" + component_name %}
{% set version = "6_6.12.0" %}
{% set version_package = version.split('_')[1] %}
{% set major_version = version.split('_')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  - url: https://github.com/ignitionrobotics/ign-{{ component_name }}/archive/ignition-{{ component_name }}{{ version }}.tar.gz
    sha256: f5538848cd89711912853ab99faa0c46ee6a4b47c17a8aa06c9814a879d4c8b8
    patches:
      - enable_win_ign.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make  # [not win]
    - cmake
    - pkg-config
    - ninja  # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    # We need protoc in build for cross-compiling
    - libprotobuf  # [build_platform != target_platform]
  host:
    - libignition-cmake2
    - libsdformat12
    - libignition-plugin1
    - libignition-transport11
    - libignition-msgs8
    - libignition-common4
    - libignition-fuel-tools7
    - libignition-gui6
    - libignition-physics5
    - libignition-sensors6
    - libignition-rendering6
    - libignition-math6
    - libignition-tools1
    - libprotobuf
    - qt-main
    - tinyxml2
    - xorg-libxfixes  # [linux]
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/{{ component_name }}{{ major_version }}/ignition/{{ component_name }}.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-{{ component_name }}{{ major_version }}/ignition-{{ component_name }}{{ major_version }}-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\\{{ component_name }}{{ major_version }}\\ignition\\{{ component_name }}.hh exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ignition-{{ component_name }}{{ major_version }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\ignition-{{ component_name }}{{ major_version }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-{{ component_name }}{{ major_version }}\\ignition-{{ component_name }}{{ major_version }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-{{ component_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Open source robotics simulator. Through Ignition Gazebo users have access to high fidelity physics, rendering, and sensor models. Additionally, users and developers have multiple points of entry to simulation including a graphical user interface, plugins, and asynchronous message passing and services.

extra:
  feedstock-name: {{ base_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
