{% set component_name = "gazebo" %}
{% set base_name = "libignition-" + component_name %}
{% set version = "5.1.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-{{ component_name }}/archive/ignition-{{ component_name }}{{ major_version }}_{{ version }}.tar.gz
    sha256: 74a093b93c6d9e4276ac5139ff5234800a604bff580f7c09bcd008646b8f02c9

build:
  number: 0
  skip: true  # [osx or win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make  # [not win]
    - cmake
    - pkg-config
    - ninja  # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - libignition-cmake2
    - libsdformat11
    - libignition-plugin1
    - libignition-transport10
    - libignition-msgs7
    - libignition-common4
    - libignition-fuel-tools6
    - libignition-gui5
    - libignition-physics4
    - libignition-sensors5
    - libignition-rendering5
    - libignition-math6
    - libignition-tools1
    - libprotobuf
    - qt
    - tinyxml2
    - xorg-libxfixes  # [linux]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/{{ component_name }}{{ major_version }}/ignition/{{ component_name }}.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-{{ component_name }}{{ major_version }}/ignition-{{ component_name }}{{ major_version }}-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\\{{ component_name }}{{ major_version }}\\ignition\\{{ component_name }}.hh exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ignition-{{ component_name }}{{ major_version }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\ignition-{{ component_name }}{{ major_version }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-{{ component_name }}{{ major_version }}\\ignition-{{ component_name }}{{ major_version }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-{{ component_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Open source robotics simulator. Through Ignition Gazebo users have access to high fidelity physics, rendering, and sensor models. Additionally, users and developers have multiple points of entry to simulation including a graphical user interface, plugins, and asynchronous message passing and services.

extra:
  feedstock-name: {{ base_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
